// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ7zWlQhnbHfSc5XpWvbT2I-d4YECHjCQ',
    appId: '1:483159378698:web:6be9a1e05297bc199908f3',
    messagingSenderId: '483159378698',
    projectId: 'flutter-todo-8d364',
    authDomain: 'flutter-todo-8d364.firebaseapp.com',
    storageBucket: 'flutter-todo-8d364.appspot.com',
    measurementId: 'G-TJXG0YJVHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvuukcFyDErtMavjmXbSFQ3ZBaEV5Ip6s',
    appId: '1:483159378698:android:d3a27cc32eb4717f9908f3',
    messagingSenderId: '483159378698',
    projectId: 'flutter-todo-8d364',
    storageBucket: 'flutter-todo-8d364.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0M3-6k8_8V-JCzFsYCXAiSapRGw7TBbs',
    appId: '1:483159378698:ios:d5adfa144a35b3c89908f3',
    messagingSenderId: '483159378698',
    projectId: 'flutter-todo-8d364',
    storageBucket: 'flutter-todo-8d364.appspot.com',
    iosClientId: '483159378698-fn0egv3o6l7e5mt510jdgbackb9vmvnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0M3-6k8_8V-JCzFsYCXAiSapRGw7TBbs',
    appId: '1:483159378698:ios:d5adfa144a35b3c89908f3',
    messagingSenderId: '483159378698',
    projectId: 'flutter-todo-8d364',
    storageBucket: 'flutter-todo-8d364.appspot.com',
    iosClientId: '483159378698-fn0egv3o6l7e5mt510jdgbackb9vmvnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );
}
